### PR TITLE
Enhance security: Do not store raw word in the HTML anymore

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by lyrixx** [comment]
Still in WIP.
* There is some issue with normalized vs not normalized word
* Speed up final unlock
* A bug about the total word when final word is found

**Comment by lyrixx** [comment]
Yeah, It should be almost OK. I fixed all main points. Now I need to 

* run the tests in the CI
* ensure I didn't broke anything

**Comment by jrmgx** [comment]
> * deal with JS vendor file (commit or not commit ?)
Commit, so the page stays the most standalone possible

**Comment by lyrixx** [comment]
I'll close this PR, because I think I'll never take time to finish it:) 

it was fun to build the secure system, but now I'm too lazy to polish everything :D 

If someone wants to continue this PR, feel free to takes my commit 👍🏼

**Comment by jrmgx** [comment]
Thank you for your time.
It was nice to see another approach to tackle the same problem.

**Pull request closed without merging**
